name: Docker Image CI

on:
  push:
    branches: [ "main" , "develop", "feature/*"]
  pull_request:
    branches: [ "main" ]

jobs:

  Test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test Lint Project by IFORM
      run: echo "test lint"
    
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)



  notify: 
    
      runs-on: ubuntu-latest

      steps: 
      - uses: actions/checkout@v4
      - name: Notification by user 
        run : echo" notify by user"

    
     
